[package]
name = "kairosdb"
version = "0.1.0"
authors = ["Kai Strempel <kstrempel@gmail.com>"]
build = "build.rs"

[features]
default = ["serde_codegen"]
unstable = ["serde_derive"]

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }

[dependencies]
hyper="^0.9"
log = "^0.3"
serde = "0.8"
serde_derive = { version = "0.8", optional = true }
serde_json = "0.8"
